### ISSUE TITLE
Update 7.6.1 fails

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/hubzilla_ynh#106]
on my two different servers HZ is not working since the last updates 

Hubzilla is up but 
- no old posts are shown
- no new post are received by the servers 
- no new items can be created

if i turn on ` ini_set('display_errors', '1');` in `/var/www/hubzilla/.htconfig.php`
several errors are shown 

e.g. on page /network

```
Warning: Undefined variable $a in /var/www/hubzilla/Zotlabs/Module/Network.php on line 211

Warning: Undefined array key "htmlhead" in /var/www/hubzilla/include/conversation.php on line 1434

Warning: Undefined array key "template" in /var/www/hubzilla/addon/gallery/gallery.php on line 78

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524
```

and on page /item 

```
`Warning: Undefined array key "conv_mode" in /var/www/hubzilla/Zotlabs/Module/Item.php on line 322

Warning: Undefined array key "group_allow" in /var/www/hubzilla/Zotlabs/Access/AccessList.php on line 

144

Warning: Undefined array key "group_allow" in /var/www/hubzilla/Zotlabs/Access/AccessList.php on line 

145

Warning: Undefined array key "contact_deny" in /var/www/hubzilla/Zotlabs/Access/AccessList.php on line 

146

Warning: Undefined array key "contact_deny" in /var/www/hubzilla/Zotlabs/Access/AccessList.php on line 

147

Warning: Undefined array key "group_deny" in /var/www/hubzilla/Zotlabs/Access/AccessList.php on line 148

Warning: Undefined array key "group_deny" in /var/www/hubzilla/Zotlabs/Access/AccessList.php on line 149

Warning: Undefined array key "verb" in /var/www/hubzilla/Zotlabs/Module/Item.php on line 725

Warning: Undefined array key "attachment" in /var/www/hubzilla/Zotlabs/Module/Item.php on line 729

Warning: Undefined array key "type" in /var/www/hubzilla/Zotlabs/Module/Item.php on line 960

Warning: Undefined array key "type" in /var/www/hubzilla/Zotlabs/Module/Item.php on line 960

Warning: Undefined variable $mid in /var/www/hubzilla/Zotlabs/Module/Item.php on line 989

Warning: Undefined array key "obj" in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1048

Warning: Undefined variable $item_starred in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1089

Warning: Undefined variable $item_uplink in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1090

Warning: Undefined variable $item_notshown in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1092

Warning: Undefined variable $item_nsfw in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1093

Warning: Undefined variable $item_relay in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1094

Warning: Undefined variable $item_mentionsme in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1095

Warning: Undefined variable $item_verified in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1098

Warning: Undefined variable $item_retained in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1099

Warning: Undefined variable $item_rss in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1100

Warning: Undefined variable $item_deleted in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1101

Warning: Undefined variable $item_hidden in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1102

Warning: Undefined variable $item_unpublished in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1103

Warning: Undefined variable $item_delayed in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1104

Warning: Undefined variable $item_pending_remove in /var/www/hubzilla/Zotlabs/Module/Item.php on line 

1105

Warning: Undefined variable $item_blocked in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1106

Warning: Undefined array key "edit" in /var/www/hubzilla/addon/wppost/wppost.php on line 55

Warning: Trying to access array offset on value of type bool in /var/www/hubzilla/extend/addon/dm42-

addons/forum/forum.php on line 815

Warning: Undefined array key "target_item" in /var/www/hubzilla/addon/diaspora/diaspora.php on line 1031

Warning: Trying to access array offset on value of type null in 

/var/www/hubzilla/addon/diaspora/diaspora.php on line 1031

Warning: Undefined array key "edit" in /var/www/hubzilla/addon/libertree/libertree.php on line 50

Warning: Undefined array key "edit" in /var/www/hubzilla/addon/pumpio/pumpio.php on line 175`
```

Don´t know - @ericgaspar does this help to identify the problem?

**Comment by rocky-III** [comment]
today did the update to YunoHost 11.0.9.13 on my Raspi Server and also some other libraries were updated

Than i tried the HZ 7.6.1 Update again... 

now it looks a bit better.. e.g.  the page /network does load now
but if i turn on ini_set('display_errors', '1'); in /var/www/hubzilla/.htconfig.php
several warnings are still shown...

the /channel page is just blank and shows this error:

`Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/www/hubzilla/include/network.php:54 Stack trace: #0 /var/www/hubzilla/include/oembed.php(281): z_fetch_url() #1 /var/www/hubzilla/include/bbcode.php(77): oembed_fetch_url() #2 [internal function]: tryoembed() #3 /var/www/hubzilla/include/bbcode.php(1262): preg_replace_callback() #4 /var/www/hubzilla/include/text.php(2069): bbcode() #5 /var/www/hubzilla/include/text.php(1782): prepare_text() #6 /var/www/hubzilla/Zotlabs/Lib/ThreadItem.php(365): prepare_body() #7 /var/www/hubzilla/Zotlabs/Lib/ThreadStream.php(223): Zotlabs\Lib\ThreadItem->get_template_data() #8 /var/www/hubzilla/include/conversation.php(923): Zotlabs\Lib\ThreadStream->get_template_data() #9 /var/www/hubzilla/Zotlabs/Module/Channel.php(490): conversation() #10 /var/www/hubzilla/Zotlabs/Web/Router.php(288): Zotlabs\Module\Channel->get() #11 /var/www/hubzilla/Zotlabs/Web/WebServer.php(108): Zotlabs\Web\Router->Dispatch() #12 /var/www/hubzilla/index.php(14): Zotlabs\Web\WebServer->run() #13 {main} thrown in /var/www/hubzilla/include/network.php on line 54`

**Comment by rocky-III** [comment]
The page /admin/    is also just blank and shows this error:

`Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/www/hubzilla/include/network.php:54 Stack trace: #0 /var/www/hubzilla/include/network.php(1744): z_fetch_url() #1 /var/www/hubzilla/Zotlabs/Module/Admin.php(133): get_repository_version() #2 /var/www/hubzilla/Zotlabs/Module/Admin.php(65): Zotlabs\Module\Admin->admin_page_summary() #3 /var/www/hubzilla/Zotlabs/Web/Router.php(288): Zotlabs\Module\Admin->get() #4 /var/www/hubzilla/Zotlabs/Web/WebServer.php(108): Zotlabs\Web\Router->Dispatch() #5 /var/www/hubzilla/index.php(14): Zotlabs\Web\WebServer->run() #6 {main} thrown in /var/www/hubzilla/include/network.php on line 54`

**Comment by rocky-III** [comment]
Update still does not work
on YunoHost -  11.0.9.15
e.g. the page  /network this kind of warnings:

`Warning: Undefined variable $a in /var/www/hubzilla/Zotlabs/Module/Network.php on line 211

Warning: Undefined array key "htmlhead" in /var/www/hubzilla/include/conversation.php on line 1434

Warning: Undefined array key "template" in /var/www/hubzilla/addon/gallery/gallery.php on line 78

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524

Warning: Cannot modify header information - headers already sent by (output started at /var/www/hubzilla/Zotlabs/Lib/Apps.php:524) in /var/www/hubzilla/boot.php on line 2453

Warning: Cannot modify header information - headers already sent by (output started at /var/www/hubzilla/Zotlabs/Lib/Apps.php:524) in /var/www/hubzilla/boot.php on line 2458

Warning: Cannot modify header information - headers already sent by (output started at /var/www/hubzilla/Zotlabs/Lib/Apps.php:524) in /var/www/hubzilla/boot.php on line 2488

Warning: Cannot modify header information - headers already sent by (output started at /var/www/hubzilla/Zotlabs/Lib/Apps.php:524) in /var/www/hubzilla/boot.php on line 2502




`
